### ISSUE TITLE
Plans for magic TAB?

### ISSUE THREAD

**Issue by jjpb44** [zshzoo/magic-enter#1]
Is possible to do the same magic but with tab? 
for example, double tab clears the terminal if input is empty.
I have been trying to implement this, but I cant achieve it.

**Comment by mattmc3** [comment]
That's probably more appropriate for a separate plugin, but this script should do what you want:

```zsh
if ! typeset -f magic-double-tab-cmd >/dev/null; then
	function magic-double-tab-cmd {
		echo 'clear'
	}
fi

function magic-double-tab {
	# Only run magic-double-tab commands when the command line is empty and
	# when on the first line (PS1)
	if ! (( $#BUFFER )) && [[ "$CONTEXT" == start ]]; then
		BUFFER=$(magic-double-tab-cmd)
		zle accept-line -w
	fi
}
zle -N magic-double-tab
bindkey '\t\t' magic-double-tab
```

**Comment by jjpb44** [comment]
Thanks @mattmc3 this is exactly what I wanted!

PD: I'm also a big fan of what you achieved with antidote plugin manager

**Comment by mattmc3** [comment]
@jujpenabe - Glad it worked! Also, thanks so much for the kind words about antidote. In truth, antidote just started because I stubbornly wanted to keep using my antibody `.zsh_plugins.txt` file, which I curated over many years of Zsh tinkering. I've really enjoyed bringing that style of Zsh plugin management back to life.
